name: Host System Tester

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.py"
      - "**.txt"

permissions:
  contents: read

jobs:
  host_macosx:
    strategy:
      matrix:
        os: [10.15, 11, 12, 13]  # macOS versions
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
          pip install -r requirements.txt
    - name: Run Tests
      run: |
          python entry.py test

  host_windows:
    strategy:
      matrix:
        os: ['windows-latest', 'windows-2022']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
          pip install -r requirements.txt
    - name: Run Tests
      run: |
          python entry.py test

  host_ubuntu:
    strategy:
      matrix:
        ubuntu_version: ['latest', '22.04', '20.04']
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
          pip install -r requirements.txt
    - name: Run Tests
      run: |
          python entry.py test
